---
title: "About project Heimdall"
---

> Heimdall 
> 
> Realms: Sight, vigilance, protection 
> 
> Heimdall was the divine guard standing watch over the Bifrost, the rainbow bridge that connects Asgard to Midgard.
> He has to blow the resounding Gjallarhorn at the start of Ragnarok to warn Asgardians of the incoming onslaught. 
> 
> Source:  [History Cooperative](https://historycooperative.org/norse-gods-and-goddesses/)

## Project Title 

**Does the attention vigilance varies on time in sensory discrimination tasks?** 

## Tasks used 

### Antisaccade task with CSI varied in millisecond steps. (AS) 

 On each trial, participants were shown for 250 ms either left or right arrow as a target, and their task was to indicate which arrow was displayed by pressing the appropriate key. The arrows were randomly displayed on either the left or right side of the screen. The stimulus was accompanied by a red dot briefly flashing on the opposite side of the screen, which should be ignored. The fixation point and the red dot/stimulus presentation were separated by a blank screen shown for CSI ranging from 400 to 900 ms.  

### Saccade-initiated inspection time task (SIIT) 

Three equidistant (15° of distance) light grey squares (each 1°×1° in size) form a centrally located triangle, heading random direction. Participants are asked to voluntarily switch between the squares and to expect at the fixated square a brief presentation of a stimulus consisting of two black vertical lines, connected at their top by a short horizontal dash (0.2°), with one random line being slightly longer at bottom (0.80°) than the other line (0.75°). The lines are presented for 60, 70, 80, or 90 ms (inspection time) and then turned to the same length (a mask) for another 740, 730, 720, or 710 ms, respectively. So, the lines plus the mask are shown on the screen always for 800 ms. The lines presentation starts from 37.5 ms to 475 ms (36 steps by 12.5 ms, 80 Hz refresh rate) after the saccade initiation. Participants have to press either the left or the right mouse button, depending on whether the left or the right line was longer, before the lines disappear from the screen (or not to press any button if missed a difference). Each trial includes 144 stimulus presentations, one per step and inspection time. Two consecutive stimulus presentations are separated by 2, 3 or 4 square switches (on random), but not less than 2 s and no more than 5 s. If participants switch too rarely, the research assistants remind them to switch more frequently (of course, a proper training session will precede the task). The trial lasts until all the 144 stimuli are presented, followed by a short break (about 8 minutes in total). At least 4, but ideally 8-10 trials are applied (20-50 stimuli per each step). 

## Experiments table 

### Asgard
**Question**: Does varying cue-stimulus interval affect the sensory discrimination performance in the antisaccade task?    
**Task**: Antisaccade   
**Data:** 40 participants, CSI range 400-900ms in 8ms step  
**Status:** Finished   
**Result**: No effect of CSI on stimulus discriminaton accuracy up to 1 sec.
 

### Bifrost 
**Question:** Does results from E1 can be stretched over other visual discrimination tasks?   
**Task:** SIIT    
**Data:** 50 participants, Eye tracking     
**Status**: Not jet prepared   
**Expected Result**: Consisted with Midgard, no effect of CSI in stimulis discrimination 

 
### Bifrost+
**Question**: Does saccade reset phase in some brain frequency?   
**Codename:** Bifrost+   
**Task:** SIIT  
**Data:** Same as in E2, but with EEG   
**Status:** No go   
**Expected Result:** Unknown


### Midgard
**Question**: Does increasing or decreasing trend (or very slow oscillations) in attention vigilance occurrs in a broader CSI range?   
**Task**: AS in CSI range from 400 to 900 ms   
**Data**: 150 Participants, collected    
**Status**: Finished    
**Result**: No effect of CSI on stimulus discriminaton accuracy in CSI range up to 1 sec.

 

### Midgard+ 
**Question**: Does increasing or decreasing trend (or very slow oscillations) in attention vigilance occurrs in a broader CSI range?     
**Codename**: Asgard+       
**Task**: AS in CSI up to 3 sec      
**Data**: Up to 300, study Y      
**Status**: No go       
**Expected Result**: No effect of CSI on stimulus discriminaton accuracy in CSI range up to 3 sec.   

 

### Gjallarhorn 
**Question:** If not attention fluctuations determine performance in visual discrimination tasks, then what? Rouder replication      
**Task:** Anti and prosaccade, inspection time, temporal order judgement appear/disappear    
**Data:** 50 participants     
**Status:** Should start 7.11.2022   
**Expected Result**: Processing speed explains (almost) all variance.     

 