---
title: "Project journal"
output: 
  html_document: 
    theme: paper
    highlight: textmate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


<ul>

<li> <details><summary>1.11.2022</summary>
 Submitting Abstract for ICPS 2023. 
 
 <h3>Title</h3>
 Varying cue-stimulus interval does not affect the sensory discrimination performance in the antisaccade task
 
 <h3> Short abstract</h3>
 Whether stimulus discrimination increases, decreases, or varies periodically as a function of cue-stimulus interval (CSI) is debated. Two experiments varied CSI in the antisaccade task between 400 and 900 ms in 8/16-ms steps. Neither trend nor oscillation in accuracy across CSIs was observed, suggesting no fluctuation of vigilance before stimulus. 
 
<h3> Suplementary abstract</h3>
 
 Whether the stimulus discrimination performance increases (e.g., due to goal strengthening), decreases (e.g., due to vigilance decay), or varies periodically (e.g., along attentional rhythms) as a function of time elapsing between task onset (fixation point, cue) and stimulus (cue-stimulus interval; CSI) is debated in the current literature on attention, and so far the findings have not been unequivocal.    
 
In order to precisely examine the role of CSI in stimulus discrimination, we used the classic antisaccade task with CSI varied in millisecond steps. On each trial, participants were shown for 250 ms either left or right arrow as a target, and their task was to indicate which arrow was displayed by pressing the appropriate key. The arrows were randomly displayed on either the left or right side of the screen. The stimulus was accompanied by a red dot briefly flashing on the opposite side of the screen, which should be ignored. The fixation point and the red dot/stimulus presentation were separated by a blank screen shown for CSI ranging from 400 to 900 ms. 
 
We conducted two experiments, one with lower resolution (less trials per participant) but a larger sample (N=150, CSI sampling frequency 60Hz) and the other with higher resolution but a smaller sample (N=40, CSI sampling frequency 120Hz). Both data sets were analyzed in the same way. For each participant, the mean accuracy was calculated for each CSI timepoint. These mean accuracy values were plotted as a function of increasing CSI, with a single curve created for each person. These curves were used to analyze the potential presence of (1) an increasing or decreasing trend, and (2) a periodic variation. The first analysis consisted of fitting a regression line for each participant. The slopes of the fitted regression were then subjected to a one-sample t-test comparing their mean with the zero value. The periodicity analysis was performed on the frequency spectrum calculated for each participant using the Fourier transform. Periodicity would be detected when the power of any of the examined frequency bands was significantly higher than the random level. The mean correctness for each subject was permuted 10,000 times, creating artificial signals that were then Fourier-transformed. Thus, the power distribution of each frequency band in the absence of periodicity was known. The comparison of the power obtained in the experiment with the permutationally determined random level was done using both Holmes adjusted and raw directional p-tests.  
 
 
 
In both experiments we observed no effect of CSI on stimulus discriminaton accuracy. Specifically, there was no increasing (linear and quadratic) trend in accuracy across CSIs, suggesting that longer preparation for the stimulus (e.g., task goal strengthening) did not improve its discrimination, as well as no respective decreasing trend, suggesting that vigilance remained constant and did not decay during almost 1 s. Crucially, there was no significant increase in the Fourier spectrum for any frequency, suggesting that vigilance did not fluctuate periodically, as assumed by influential theories of attentional rhythms presumed to oscillate in the delta/theta band, at least when we filtered the data in the valid way (unlike several studies which reported such oscillations, but used invalid filtering).
 
Taken together, our very precise and comprehensively analyzed data help to clarify the workings of attention when expecting a stimulus (i.e., vigilance functioning during CSI). In particular, all the models in question: task goal strengthening, vigilance decay, and oscillatory fluctuation, were not supported by our data. Vigilance, at least in the antisaccade task, seems to be constant up to 900 ms before stimulus presentation. Thus, existing models of attention in stimulus discrimination may need reconsideration. Other tasks and larger CSI ranges (above 1 s) should be investigated in the future studies. 
</details>
</li>

<li> <details><summary>29.10.2022</summary>
E-mail exchange defining a big picture and milestones for the whole project. Described in **About** section. 
</details>
</li>

<li> <details><summary>25.10.2022</summary>
 Over a 2 hour online meeting about general idea of the project. 
</details>
</li>

</ul>