# All values in no. of frames.
TRAINING_TRIALS: [ 10, 10 ]
TRAINING_SOAS: [ 20, 10 ]
# both above list must be equal in length
START_SOA: 10
FIX_TIME: 45 # Fixation cross time
MTIME: 17 # Mask presentation time
RTIME: 240 # Maximal response time
RESTTIME: 240
REST_TIME_RANGE: [ 45, 60 ]
MAX_REVS: 10 # No of reversals in adaptive alg.
N_UP: 2
N_DOWN: 1
